name: Reproduce the same image over and over and over

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:

jobs:
  local-build:
    name: Reproducibly build image in ubuntu-${{ matrix.variant }} using ${{ matrix.extra.runtime }}
    strategy:
      matrix:
        variant:
          - "24.04"
          - "22.04"
        buildkit:
          - "docker.io/moby/buildkit:v19.0@sha256:14aa1b4dd92ea0a4cd03a54d0c6079046ea98cd0c0ae6176bdd7036ba370cbbe"
          - "docker.io/moby/buildkit:latest"
        extra:
          - runtime: "docker"
            args: --buildx-args "--platform linux/amd64,linux/arm64"
          - runtime: "podman"
            args: --buildkit-args "--opt platform=linux/amd64,linux/arm64"
    runs-on: ubuntu-${{ matrix.variant }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Intall Podman
        if: matrix.extra.runtime == 'podman'
        run: |
          sudo apt update
          sudo apt install -y podman

      - name: Build image
        run: |
          sudo ./repro-build build  \
            --buildkit-image \
            ${{ matrix.buildkit }} \
            --source-date-epoch \
            1677619260 \
            --runtime \
            ${{ matrix.extra.runtime }} \
            ${{ matrix.extra.args }} \
            -t \
            image:latest \
            -f \
            Dockerfile.debian-12 \
            .

      - name: Verify digest
        run: |
          ./repro-build analyze \
            --expected-image-digest \
            sha256:fab23b1d46130ff2086e95f412c9604204bdff3b41d5ca0cacbe564887bb5075 \
            image.tar

  actions-build:
    name: Reproducibly build image in ubuntu-${{ matrix.variant }} using Docker Buildx action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - "24.04"
          - "22.04"
        buildkit:
          - "docker.io/moby/buildkit:v19.0@sha256:14aa1b4dd92ea0a4cd03a54d0c6079046ea98cd0c0ae6176bdd7036ba370cbbe"
          - "docker.io/moby/buildkit:latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: image=${{ matrix.buildkit }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          provenance: false
          build-args: SOURCE_DATE_EPOCH=1677619260
          outputs: type=oci,dest=image.tar,name=image:latest,rewrite-timestamp=true
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.debian-12

      - name: Verify digest
        run: |
          ./repro-build analyze \
            --expected-image-digest \
            sha256:fab23b1d46130ff2086e95f412c9604204bdff3b41d5ca0cacbe564887bb5075 \
            image.tar
